=== pypi-data/pypi-mirror-345/packages/s1aux/s1aux-0.9.tar.gz/s1aux-0.9/tests/data/v1.05/S1B_AUX_ITC_V20160422T000000_G20221003T125747.SAFE/support/s1-aux-itc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.5">
  <xsd:include schemaLocation="s1-object-types.xsd"/>
  <xsd:complexType name="instrumentTimingCalibrationType">
    <xsd:annotation>
      <xsd:documentation>Channel dependent instrument timing calibration parameters for the SETAP product.</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="swath" type="swathType">
        <xsd:annotation>
          <xsd:documentation>Canonical name of the swath to which this set of internal calibration parameters applies. The swath and polarisation are used to index the applicable internalCalibrationParams record. </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="polarisation" type="polarisationType">
        <xsd:annotation>
          <xsd:documentation>Polarisation to which this set of internal calibration parameters applies. The polarisation andUsed along with the swathNumber are used to index the applicable internalCalibrationParams record.</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="rangeCalibration" type="double">
        <xsd:annotation>
          <xsd:documentation>SETAP range calibration[s].</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="azimuthCalibration" type="double">
        <xsd:annotation>
          <xsd:documentation>SETAP azimuth calibration [s].</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="instrumentTimingCalibrationListType">
    <xsd:annotation>
      <xsd:documentation>Timing calibration parameters list for the SETAP processor. This element contains a list of swath/polarisation channel dependent instrument parameters. There is an entry for each swath/polarisation combination for a total of 56. The SPPDU document defines an additional 68 swath number codes that can be used if required.</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="instrumentTimingCalibration" type="instrumentTimingCalibrationType" maxOccurs="56">
        <xsd:annotation>
          <xsd:documentation>Instrument timing calibration parameters. This record contains swath/polarisation channel dependent parameters related to the instrument. There may be up to one record per swath (23 nominal swaths) per polarisation (4 polarisation combinations for SM, IW, EW) for a maximum total of 56.</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="count" type="unsignedInt" use="required">
      <xsd:annotation>
        <xsd:documentation>Number of internalCalibrationParam records in the list.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="auxiliarySetapType">
    <xsd:annotation>
      <xsd:documentation>Root element</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="instrumentTimingCalibrationList" type="instrumentTimingCalibrationListType"/>
    </xsd:sequence>
    <xsd:attribute name="schemaVersion" type="xsd:decimal" use="required" fixed="1.5"/>
  </xsd:complexType>
  <xsd:element name="auxiliarySetap" type="auxiliarySetapType">
    <xsd:annotation>
      <xsd:documentation>SETAP auxiliary file definition (AUX_ITC).  This file includes information related to the instrument timing calibration.  It is annotated to the S1 ETAD product.</xsd:documentation>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>

=== pypi-data/pypi-mirror-345/packages/s1aux/s1aux-0.9.tar.gz/s1aux-0.9/tests/data/v1.05/S1B_AUX_ITC_V20160422T000000_G20221003T125747.SAFE/data/s1b-aux-itc.xml
<?xml version='1.0' encoding='UTF-8'?>
<auxiliarySetap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1.5" xsi:noNamespaceSchemaLocation="../support/s1-aux-itc.xsd">
  <instrumentTimingCalibrationList count="56">
    <instrumentTimingCalibration>
      <swath>S1</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S1</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S1</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S1</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S2</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S2</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S2</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S2</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S3</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S3</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S3</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S3</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S4</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S4</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S4</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S4</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S5</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S5</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S5</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S5</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S6</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S6</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S6</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>S6</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW1</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW1</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW1</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW1</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW2</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW2</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW2</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW2</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW3</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW3</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW3</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>IW3</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>EW1</swath>
      <polarisation>HH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>EW1</swath>
      <polarisation>HV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>EW1</swath>
      <polarisation>VV</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
    </instrumentTimingCalibration>
    <instrumentTimingCalibration>
      <swath>EW1</swath>
      <polarisation>VH</polarisation>
      <rangeCalibration>6.4566e-11</rangeCalibration>
      <azimuthCalibration>-4.9701e-05</azimuthCalibration>
