=== pypi-data/pypi-mirror-345/packages/s1aux/s1aux-0.9.tar.gz/s1aux-0.9/tests/data/v1.05/S1__AUX_SCF_V20140406T133000_G20221003T130002.SAFE/support/s1--aux-scf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.5">
  <xsd:complexType name="listOfGlobalParamsType">
    <xsd:sequence>
      <xsd:element name="troposphericDelayCorrection" type="xsd:boolean" default="true"/>
      <xsd:element name="ionosphericDelayCorrection" type="xsd:boolean" default="true"/>
      <xsd:element name="solidEarthTideCorrection" type="xsd:boolean" default="true"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="generalProcessorConfType">
    <xsd:sequence>
      <xsd:element name="listOfGlobalParams" type="listOfGlobalParamsType"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="listOfModeParamsType">
    <xsd:sequence>
      <xsd:element name="correctionGridRangeSampling" default="200">
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:short">
              <xsd:attribute name="unit" type="xsd:string" use="required"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="correctionGridAzimuthSampling" default="200">
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:short">
              <xsd:attribute name="unit" type="xsd:string" use="required"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="bistaticAzimuthCorrection" type="xsd:boolean" default="true"/>
      <xsd:element name="dopplerShiftRangeCorrection" type="xsd:boolean"/>
      <xsd:element name="fmMismatchAzimuthCorrection" type="xsd:boolean"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="listOfModesType">
    <xsd:sequence>
      <xsd:element name="mode" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="listOfModeParams" type="listOfModeParamsType"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="count" type="xsd:short" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="modeRelatedConfType">
    <xsd:sequence>
      <xsd:element name="listOfModes" type="listOfModesType"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="setapConfType">
    <xsd:annotation>
      <xsd:documentation>Root element</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="generalProcessorConf" type="generalProcessorConfType"/>
      <xsd:element name="modeRelatedConf" type="modeRelatedConfType"/>
    </xsd:sequence>
    <xsd:attribute name="schemaVersion" type="xsd:decimal" use="required" fixed="1.5"/>
  </xsd:complexType>
  <xsd:element name="setapConf" type="setapConfType">
    <xsd:annotation>
      <xsd:documentation>SETAP configuration auxiliary file definition (AUX_SCF).</xsd:documentation>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>

=== pypi-data/pypi-mirror-345/packages/s1aux/s1aux-0.9.tar.gz/s1aux-0.9/tests/data/v1.05/S1__AUX_SCF_V20140406T133000_G20221003T130002.SAFE/data/s1--aux-scf.xml
<?xml version='1.0' encoding='UTF-8'?>
<setapConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1.5" xsi:noNamespaceSchemaLocation="../support/s1--aux-scf.xsd">
  <generalProcessorConf>
    <listOfGlobalParams>
      <troposphericDelayCorrection>true</troposphericDelayCorrection>
      <ionosphericDelayCorrection>true</ionosphericDelayCorrection>
      <solidEarthTideCorrection>true</solidEarthTideCorrection>
    </listOfGlobalParams>
  </generalProcessorConf>
  <modeRelatedConf>
    <listOfModes count="3">
      <mode>
        <name>S1-ETAD-SM</name>
        <listOfModeParams>
          <correctionGridRangeSampling unit="m">200</correctionGridRangeSampling>
          <correctionGridAzimuthSampling unit="m">200</correctionGridAzimuthSampling>
          <bistaticAzimuthCorrection>true</bistaticAzimuthCorrection>
          <dopplerShiftRangeCorrection>false</dopplerShiftRangeCorrection>
          <fmMismatchAzimuthCorrection>false</fmMismatchAzimuthCorrection>
        </listOfModeParams>
      </mode>
      <mode>
        <name>S1-ETAD-IW</name>
        <listOfModeParams>
          <correctionGridRangeSampling unit="m">200</correctionGridRangeSampling>
          <correctionGridAzimuthSampling unit="m">200</correctionGridAzimuthSampling>
          <bistaticAzimuthCorrection>true</bistaticAzimuthCorrection>
          <dopplerShiftRangeCorrection>true</dopplerShiftRangeCorrection>
          <fmMismatchAzimuthCorrection>true</fmMismatchAzimuthCorrection>
        </listOfModeParams>
      </mode>
      <mode>
        <name>S1-ETAD-EW</name>
        <listOfModeParams>
          <correctionGridRangeSampling unit="m">200</correctionGridRangeSampling>
          <correctionGridAzimuthSampling unit="m">200</correctionGridAzimuthSampling>
          <bistaticAzimuthCorrection>true</bistaticAzimuthCorrection>
          <dopplerShiftRangeCorrection>true</dopplerShiftRangeCorrection>
          <fmMismatchAzimuthCorrection>true</fmMismatchAzimuthCorrection>
        </listOfModeParams>
      </mode>
    </listOfModes>
  </modeRelatedConf>
</setapConf>
